#! /usr/bin/env bash

# This script initializes the system for local usage

set -e
cd "${0%/*}"
ROOT="$(pwd)"

check() {
	if ! command -v "$1" >& /dev/null; then
		echo "'$1' is not installed. Please install '$1'"
		exit 1
	fi
	echo "'$1' found"
}

check cargo
check git
check npm
check rustc

git submodule update --init --recursive
cd files/jquery
npm run build
