#! /usr/bin/env bash

# This script initializes the system for local usage

set -e
cd "${0%/*}"

if ! command -v npm >& /dev/null; then
	echo "'npm' is not installed. Please install 'npm'"
	exit 1
fi

git submodule update --init --recursive
cd files/jquery
npm run build
