#! /usr/bin/env bash

# This script initializes the system for local usage

# We make sure that the bash script stops on errors
set -e

# Update all submodules
git submodule update --init --recursive
